
	.var USES_EXOMIZED_DATA	= 		false

	.const SCREEN_FRONT_BUFFER =	$c000
	.const SCREEN_BACK_BUFFER =		$c400
	.const GAME_CHARACTERS =		$c800
	.const GFX_DD00	 = 				%00000000

	.const JOY_UP =					0
	.const JOY_DOWN =				1
	.const JOY_LEFT =				2
	.const JOY_RIGHT =				3
	.const JOY_FIRE =				4

	.const MAX_NO_MAINBULLETS  		=	2 * 7
	.const MAIN_BULLET_CHARACTER	=	2

	.const TRANSITION_NONE = 				0
	.const TRANSITION_FADEOUT_BLACK = 		1
	.const TRANSITION_FADEBAR_WHITE = 		2
	.const TRANSITION_FADEIN_BLACK = 		3

	.const NUMBER_OF_ROOMS_POINTER	=		0
	.const PALETTE_POINTER			=		1
	.const ROOM_0_SIZE_POINTER		=		37
	.const ROOM_0_DATA_START		=		38

	.const FRAME_MAIN_FLY_START		=		64
	.const FRAME_MAIN_FLY_END		=		72
	.const MAIN_SPRITE_WIDTH		=		24
	.const MAIN_SPRITE_HEIGHT		=		21

	.const MAIN_BORDER_UP			=		42
	.const MAIN_BORDER_DOWN			=		234
	.const MAIN_BORDER_LEFT			=		20
	.const MAIN_BORDER_RIGHT		=		88 - 24 - 12

	.const FRAME_MAIN_START			=		64
	.const FRAMES_IN_MAIN			=		40

	.const FRAME_ENEMIES_START		=		FRAME_MAIN_START + FRAMES_IN_MAIN

	.const NUMBER_OF_SMUX_SPRITES	=		16
	.const SPRITE_BUFFER_0			=		0
	.const SPRITE_BUFFER_1			=		NUMBER_OF_SMUX_SPRITES

	.const ZERO_PAGE_0_IN_IRQ			=		$73
	.const ZERO_PAGE_1_IN_IRQ			=		$74
	.const ZERO_PAGE_2_IN_IRQ			=		$75

	.const SPRITE_ZERO_PAGE_X_COORD		=		$76
	.const SPRITE_ZERO_PAGE_X_MSB_COORD	=		$77
	.const SPRITE_ZERO_PAGE_Y_COORD		=		$78
	.const SPRITE_ZERO_PAGE_COLOR		=		$79
	.const SPRITE_ZERO_PAGE_FRAME		=		$7a

	.const NUMBER_OF_OBJECTS			=		16	// Number of concurrent obejcts on screen
	.const OBJECT_ZERO_PAGE_TYPE		=		$76
	.const OBJECT_ZERO_PAGE_X_COORD		=		$77
	.const OBJECT_ZERO_PAGE_X_MSB_COORD	=		$78
	.const OBJECT_ZERO_PAGE_Y_COORD		=		$79
	.const OBJECT_ZERO_PAGE_COLOR		=		$7a
	.const OBJECT_ZERO_PAGE_PROPERTY_1	=		$7b
	.const OBJECT_ZERO_PAGE_PROPERTY_2	=		$7c

	.const OBJECT_ROUTINE_CREATE		=		0
	.const OBJECT_ROUTINE_UPDATE		=		3
	.const OBJECT_ROUTINE_DEAD			=		6
	.const OBJECT_ROUTINE_DRAW			=		9

	.const NUMBER_OF_ANIMATIONS			=		NUMBER_OF_OBJECTS
	.const ANIMATION_ZERO_PAGE_TYPE		=		$76
	.const ANIMATION_ZERO_PAGE_START_FRAME	=	$77
	.const ANIMATION_ZERO_PAGE_END_FRAME	=	$78
	.const ANIMATION_ZERO_PAGE_SPEED		=	$79

	.const ANIMATION_TYPE_NONE				=	0
	.const ANIMATION_TYPE_ONCE_STAND		=	1
	.const ANIMATION_TYPE_ONCE_DIE			=	2
	.const ANIMATION_TYPE_LOOP				=	3
	.const ANIMATION_TYPE_PINGPONG			=	4

	.const COLLISION_WITH_NONE				=	0
	.const COLLISION_WITH_MAIN				=	1
	.const COLLISION_WITH_MAINBULLET		=	2

	.const COLLISION_ZERO_PAGE_A_X1			=	$76
	.const COLLISION_ZERO_PAGE_A_X1_MSB		=	$77
	.const COLLISION_ZERO_PAGE_A_X2			=	$78
	.const COLLISION_ZERO_PAGE_A_X2_MSB		=	$79
	.const COLLISION_ZERO_PAGE_B_X1			=	$7a
	.const COLLISION_ZERO_PAGE_B_X1_MSB		=	$7b
	.const COLLISION_ZERO_PAGE_B_X2			=	$7c
	.const COLLISION_ZERO_PAGE_B_X2_MSB		=	$7d
	.const COLLISION_ZERO_PAGE_A_Y1			=	$7e
	.const COLLISION_ZERO_PAGE_A_Y2			=	$7f
	.const COLLISION_ZERO_PAGE_B_Y1			=	$80
	.const COLLISION_ZERO_PAGE_B_Y2			=	$81

